name: "网易云音乐API增强版"
description: "全网最全的网易云音乐API接口，支持几乎所有网易云音乐功能"
version: "4.29.20"
slug: "netease-cloud-music-api-enhanced"
init: false
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
startup: services
boot: auto
devicetree: false
host_network: false
privileged:
  - NET_ADMIN
environment:
  - TZ=Asia/Shanghai
map:
  - config:rw
  - ssl:ro
options:
  port: 3000
  log_level: "info"
schema:
  port: port
  log_level: list("trace", "debug", "info", "warning", "error", "fatal")
documentation: https://github.com/Vincent1994Go/addons/blob/main/netease-cloud-music-api-enhanced/README.md
# logo: https://raw.githubusercontent.com/Vincent1994Go/addons/main/netease-cloud-music-api-enhanced/logo.png
icon: mdi:music
url: https://github.com/Vincent1994Go/addons
maintainer: Vincent1994Go <your-email@example.com>
